export default {
  name: 'The Boys',
  next_episode_to_air: {
    air_date: '2022-06-30',
    episode_number: 7,
    id: 3435048,
    name: '',
    overview: '',
    production_code: '',
    runtime: 60,
    season_number: 3,
    still_path: null,
    vote_average: 0.0,
    vote_count: 0,
  },
  networks: [
    {
      id: 1024,
      name: 'Amazon',
      logo_path: '/ifhbNuuVnlwYy5oXA5VIb2YR8AZ.png',
      origin_country: '',
    },
  ],
  number_of_episodes: 24,
  number_of_seasons: 3,
  origin_country: ['US'],
  original_language: 'en',
  original_name: 'The Boys',
  overview:
    'Na trama, conhecemos um mundo em que super-heróis são as maiores celebridades do planeta, e rotineiramente abusam dos seus poderes ao invés de os usarem para o bem.',
  popularity: 3476.228,
  poster_path: '/stTEycfG9928HYGEISBFaG1ngjM.jpg',
  production_companies: [
    {
      id: 20580,
      logo_path: '/oRR9EXVoKP9szDkVKlze5HVJS7g.png',
      name: 'Amazon Studios',
      origin_country: 'US',
    },
    {
      id: 333,
      logo_path: '/5xUJfzPZ8jWJUDzYtIeuPO4qPIa.png',
      name: 'Original Film',
      origin_country: 'US',
    },
    {
      id: 11073,
      logo_path: '/wHs44fktdoj6c378ZbSWfzKsM2Z.png',
      name: 'Sony Pictures Television Studios',
      origin_country: 'US',
    },
    {
      id: 38398,
      logo_path: null,
      name: 'Kripke Enterprises',
      origin_country: 'US',
    },
    {
      id: 16615,
      logo_path: '/dbxHaOtibTKvP6dUMRYdwUOULgY.png',
      name: 'Point Grey Pictures',
      origin_country: 'US',
    },
    {
      id: 2526,
      logo_path: '/kzIW6QWhacDwzGoXEIWhac8rb70.png',
      name: 'Kickstart',
      origin_country: 'US',
    },
    {
      id: 33728,
      logo_path: null,
      name: 'NightSky Productions',
      origin_country: 'US',
    },
    {
      id: 40457,
      logo_path: null,
      name: 'Amazon Productions',
      origin_country: 'US',
    },
  ],
  production_countries: [
    { iso_3166_1: 'US', name: 'United States of America' },
  ],
  seasons: [
    {
      air_date: '2020-09-10',
      episode_count: 19,
      id: 163277,
      name: 'Especiais',
      overview: '',
      poster_path: '/cCXG81dSCPXcqYm6gTHlwtXocti.jpg',
      season_number: 0,
    },
    {
      air_date: '2019-07-25',
      episode_count: 8,
      id: 98085,
      name: 'Temporada 1',
      overview:
        'THE BOYS é uma visão irreverente do que acontece quando super-heróis, que são tão populares quanto celebridades, tão influentes quanto políticos e tão reverenciados como Deuses, abusam de seus superpoderes ao invés de usá-los para o bem. É o sem poder contra o superpoder, quando os rapazes embarcam em uma jornada heroica para expor a verdade sobre "Os Sete" com o apoio da Vought.',
      poster_path: '/3PhOp6IH74m1Np7P8UVwdsQgRnn.jpg',
      season_number: 1,
    },
    {
      air_date: '2020-09-03',
      episode_count: 8,
      id: 154681,
      name: 'Temporada 2',
      overview:
        'Em uma segunda temporada mais intensa e mais desesperada de THE BOYS, Butcher, Hughie e a equipe se recuperam de suas perdas na primeira temporada. Fugindo da lei, eles sofrem para lutar contra os Super-heróis. Enquanto Vought, a empresa que gerencia os heróis, entra em pânico com a ameaça dos Supervilões, e uma nova heroína, Stormfront, agita a empresa e desafia um Homelander já instável.',
      poster_path: '/9Sa3WBsTnJRK8PlKym4N9wUodIT.jpg',
      season_number: 2,
    },
    {
      air_date: '2022-06-02',
      episode_count: 8,
      id: 215686,
      name: '3ª Temporada',
      overview: '',
      poster_path: '/ut4PhX7OP2l2oJhrIUYWnt9pnQU.jpg',
      season_number: 3,
      networks: [
        {
          id: 1024,
          logo: {
            path: '/ifhbNuuVnlwYy5oXA5VIb2YR8AZ.png',
            aspect_ratio: 3.242914979757085,
          },
          name: 'Amazon',
          origin_country: '',
        },
      ],
    },
  ],
  spoken_languages: [
    { english_name: 'English', iso_639_1: 'en', name: 'English' },
  ],
  status: 'Returning Series',
  tagline: 'Nunca conheça seus heróis.',
  type: 'Scripted',
  vote_average: 8.4,
  vote_count: 6309,
};
